# Generated by Django 4.2.13 on 2024-06-30 02:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phoneNumber", models.CharField(blank=True, max_length=20)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("lastname", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=128)),
                ("emailLogin", models.EmailField(max_length=254, unique=True)),
                ("year", models.CharField(blank=True, max_length=4, null=True)),
                ("month", models.CharField(blank=True, max_length=2, null=True)),
                ("day", models.CharField(blank=True, max_length=2, null=True)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goTogether.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("route", models.TextField(blank=True)),
                ("travel_date", models.DateField()),
                ("pickup_time", models.TimeField()),
                ("passenger_count", models.PositiveIntegerField(default=1)),
                ("price_per_seat", models.PositiveIntegerField(default=1)),
                ("checked_items", models.JSONField(default=dict)),
                ("is_reservation_enabled", models.BooleanField(default=False)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goTogether.user",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goTogether.vehicle",
                    ),
                ),
            ],
        ),
    ]
