# Generated by Django 4.2.13 on 2024-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goTogether", "0002_car_alter_trip_vehicle_delete_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
