# Generated by Django 4.2.13 on 2024-07-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goTogether", "0003_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="route",
        ),
    ]
