# Generated by Django 4.2.13 on 2024-07-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goTogether", "0004_remove_trip_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="duration",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="trip",
            name="destination",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
