# Generated by Django 4.2.13 on 2024-07-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goTogether", "0005_trip_duration_alter_trip_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="duration",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="trip",
            name="origin",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
