# Generated by Django 4.2.13 on 2024-07-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goTogether", "0006_alter_trip_duration_alter_trip_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="arrival_time",
            field=models.TimeField(default="10:00:00"),
        ),
    ]
