# Generated by Django 4.2.13 on 2024-07-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goTogether", "0007_trip_arrival_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="arrival_time",
            field=models.TimeField(),
        ),
    ]
