# Generated by Django 4.2.13 on 2024-07-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goTogether", "0008_alter_trip_arrival_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="brand",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="car",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="car",
            name="passengers",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="car",
            name="plate",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="car",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
